In [30]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

## Grab dataset

In [35]:
data=pd.read_csv('/content/Housing Pricing.csv')

In [36]:
data

        Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0        1          60       RL  ...        WD         Normal    208500
1        2          20       RL  ...        WD         Normal    181500
2        3          60       RL  ...        WD         Normal    223500
3        4          70       RL  ...        WD        Abnorml    140000
4        5          60       RL  ...        WD         Normal    250000
...    ...         ...      ...  ...       ...            ...       ...
1455  1456          60       RL  ...        WD         Normal    175000
1456  1457          20       RL  ...        WD         Normal    210000
1457  1458          70       RL  ...        WD         Normal    266500
1458  1459          20       RL  ...        WD         Normal    142125
1459  1460          20       RL  ...        WD         Normal    147500

[1460 rows x 77 columns]

In [37]:
data.shape

(1460, 77)

In [38]:
data.drop('Id',axis=1,inplace=True)

In [39]:
data.head

<bound method NDFrame.head of       MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
0             60       RL         65.0  ...        WD        Normal    208500
1             20       RL         80.0  ...        WD        Normal    181500
2             60       RL         68.0  ...        WD        Normal    223500
3             70       RL         60.0  ...        WD       Abnorml    140000
4             60       RL         84.0  ...        WD        Normal    250000
...          ...      ...          ...  ...       ...           ...       ...
1455          60       RL         62.0  ...        WD        Normal    175000
1456          20       RL         85.0  ...        WD        Normal    210000
1457          70       RL         66.0  ...        WD        Normal    266500
1458          20       RL         68.0  ...        WD        Normal    142125
1459          20       RL         75.0  ...        WD        Normal    147500

[1460 rows x 76 columns]>

In [40]:
original_features=list(data.columns)
original_features

['MSSubClass',
 'MSZoning',
 'LotFrontage',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'KitchenQual',
 'TotRmsAbvGrd',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleType',
 'SaleCondition',
 'SalePrice']

In [41]:
features_with_missing=list(data.columns[data.isna().any()])
features_with_missing

['LotFrontage',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [42]:
for feature in features_with_missing:
  print(feature,' ',(data[feature].isna().sum())/len(data)*100)

LotFrontage   17.73972602739726
MasVnrType   0.547945205479452
MasVnrArea   0.547945205479452
BsmtQual   2.5342465753424657
BsmtCond   2.5342465753424657
BsmtExposure   2.6027397260273974
BsmtFinType1   2.5342465753424657
BsmtFinType2   2.6027397260273974
Electrical   0.0684931506849315
FireplaceQu   47.26027397260274
GarageType   5.5479452054794525
GarageYrBlt   5.5479452054794525
GarageFinish   5.5479452054794525
GarageQual   5.5479452054794525
GarageCond   5.5479452054794525

drop any feature thats has more the 0.5 missing values

In [43]:
data.dropna(axis=1, thresh=0.5*(len(data)),inplace=True)

In [44]:
features_with_missing

['LotFrontage',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [45]:
mean_fill=['LotFrontage','MasVnrType']
bfill=['FireplaceQu']
ffill=list(set(features_with_missing)-set(mean_fill)-set(bfill))

In [46]:
for feature in mean_fill:
  data[feature].fillna(data[feature].mean(),inplace=True)

TypeError: ignored

In [28]:
for feature in ffill:
  data[feature].fillna(method='ffill',inplace=True)

In [47]:
for feature in bfill:
  data[feature].fillna(method='bfill',inplace=True)

In [48]:
data.isna().any()

MSSubClass       False
MSZoning         False
LotFrontage      False
LotArea          False
Street           False
                 ...
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 76, dtype: bool

Encode the dataset

In [49]:
data.dtypes

MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 76, dtype: object

In [50]:
cat_data=data.select_dtypes(include=['object']).copy()
cat_data.head(2)

  MSZoning Street LotShape  ... PavedDrive SaleType SaleCondition
0       RL   Pave      Reg  ...          Y       WD        Normal
1       RL   Pave      Reg  ...          Y       WD        Normal

[2 rows x 39 columns]

In [51]:
cat_features=list(cat_data.columns)
cat_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [52]:
nominal=['MSZoning','LandContour','LotConfig','Neighborhood']
ordinal=list(set(cat_features)-set(nominal))
numerical=list(set(original_features)-set(cat_features))
target=['SalePrice']

In [53]:
data[target]

      SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [54]:
for feature in ordinal:
  data[feature]=(data[feature].astype('category')).cat.codes

Change4 ordinal to categorical to do numerical encoding above

In [55]:
df_nominal=pd.get_dummies(data[nominal])

In [56]:
df_ordinal=data[ordinal]

In [57]:
df_numerical=data[numerical]

In [58]:
encoded_data=pd.concat([df_numerical])

In [59]:
encoded_data.shape

(1460, 37)

In [60]:
encoded_data['SalePrice']

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [61]:
x=encoded_data.drop('SalePrice',axis=1)

In [62]:
y=data[target]

In [63]:
x=x.to_numpy()
x

array([[1.960e+02, 8.450e+03, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        7.060e+02],
       [0.000e+00, 9.600e+03, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        9.780e+02],
       [1.620e+02, 1.125e+04, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        4.860e+02],
       ...,
       [0.000e+00, 9.042e+03, 2.000e+00, ..., 0.000e+00, 0.000e+00,
        2.750e+02],
       [0.000e+00, 9.717e+03, 0.000e+00, ..., 0.000e+00, 1.029e+03,
        4.900e+01],
       [0.000e+00, 9.937e+03, 0.000e+00, ..., 0.000e+00, 2.900e+02,
        8.300e+02]])

In [64]:
y=y.to_numpy()
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [65]:
x=StandardScaler().fit_transform(x)
y=StandardScaler().fit_transform(y)

In [66]:
for feature in cat_features:
  (data[feature].astype('category')).cat.codes

In [67]:
data[nominal]

     MSZoning LandContour LotConfig Neighborhood
0          RL         Lvl    Inside      CollgCr
1          RL         Lvl       FR2      Veenker
2          RL         Lvl    Inside      CollgCr
3          RL         Lvl    Corner      Crawfor
4          RL         Lvl       FR2      NoRidge
...       ...         ...       ...          ...
1455       RL         Lvl    Inside      Gilbert
1456       RL         Lvl    Inside       NWAmes
1457       RL         Lvl    Inside      Crawfor
1458       RL         Lvl    Inside        NAmes
1459       RL         Lvl    Inside      Edwards

[1460 rows x 4 columns]

In [68]:
data[numerical]

      MasVnrArea  LotArea  Fireplaces  ...  PoolArea  BsmtFinSF2  BsmtFinSF1
0          196.0     8450           0  ...         0           0         706
1            0.0     9600           1  ...         0           0         978
2          162.0    11250           1  ...         0           0         486
3            0.0     9550           1  ...         0           0         216
4          350.0    14260           1  ...         0           0         655
...          ...      ...         ...  ...       ...         ...         ...
1455         0.0     7917           1  ...         0           0           0
1456       119.0    13175           2  ...         0         163         790
1457         0.0     9042           2  ...         0           0         275
1458         0.0     9717           0  ...         0        1029          49
1459         0.0     9937           0  ...         0         290         830

[1460 rows x 37 columns]

In [70]:
pd.get_dummies